# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AlpaconCli < Formula
  desc "Alpacon CLI"
  homepage "https://github.com/alpacax/alpacon-cli"
  version "0.4.5"

  on_macos do
    on_intel do
      url "https://github.com/alpacax/alpacon-cli/releases/download/v0.4.5/alpacon-0.4.5-darwin-amd64.tar.gz"
      sha256 "8c4a59432c39ad42da29dd90501f9c40dee92467c71e563b7f0bb2301bc26799"

      def install
        bin.install "alpacon"
      end
    end
    on_arm do
      url "https://github.com/alpacax/alpacon-cli/releases/download/v0.4.5/alpacon-0.4.5-darwin-arm64.tar.gz"
      sha256 "b7d42da75e7f3b7aee71874ada936a0826b6c3aa910de985e7002e0aafe1f77c"

      def install
        bin.install "alpacon"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/alpacax/alpacon-cli/releases/download/v0.4.5/alpacon-0.4.5-linux-amd64.tar.gz"
        sha256 "649ecc481a4a320c20621d7ee5c48c6524446245621ef0b06773434c0e7ca5ad"

        def install
          bin.install "alpacon"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/alpacax/alpacon-cli/releases/download/v0.4.5/alpacon-0.4.5-linux-arm.tar.gz"
        sha256 "efc4862dfeff576fa5130bebcf02f9204dda4b9beeabca39ac8a01f460726c08"

        def install
          bin.install "alpacon"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/alpacax/alpacon-cli/releases/download/v0.4.5/alpacon-0.4.5-linux-arm64.tar.gz"
        sha256 "d8f5627f02b0088c6202b64fd46017bbba937510e257ebca543a3aae57046c44"

        def install
          bin.install "alpacon"
        end
      end
    end
  end
end
