# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AlpaconCli < Formula
  desc "Command-line client for Alpacon (Websh, exec, file transfer, tunnels)"
  homepage "https://github.com/alpacax/alpacon-cli"
  version "1.7.1"

  on_macos do
    on_intel do
      url "https://github.com/alpacax/alpacon-cli/releases/download/v1.7.1/alpacon-1.7.1-darwin-amd64.tar.gz"
      sha256 "ba2aff15aa70e1bd5a6a91b2c785e3221c9294af8faad345b32d88ea027db87a"

      def install
        bin.install "alpacon"
      end
    end
    on_arm do
      url "https://github.com/alpacax/alpacon-cli/releases/download/v1.7.1/alpacon-1.7.1-darwin-arm64.tar.gz"
      sha256 "577bbe86c09cda2ee2a851acbcc319ea7786236c58bd80c4d51e5da6aba6c320"

      def install
        bin.install "alpacon"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/alpacax/alpacon-cli/releases/download/v1.7.1/alpacon-1.7.1-linux-amd64.tar.gz"
        sha256 "2c76f5ba2c994a08c2c0318b2d896136ff944f32b495c36e649114769cb6ee43"

        def install
          bin.install "alpacon"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/alpacax/alpacon-cli/releases/download/v1.7.1/alpacon-1.7.1-linux-arm.tar.gz"
        sha256 "7050155a698bab82dc0186bcc2dc1f96e21b7525375a7fd940de85f41b13b2ea"

        def install
          bin.install "alpacon"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/alpacax/alpacon-cli/releases/download/v1.7.1/alpacon-1.7.1-linux-arm64.tar.gz"
        sha256 "97f4c9074739ee83748ef319cb4d41aa6dc8c36027845de3fbace8cea005f8a0"

        def install
          bin.install "alpacon"
        end
      end
    end
  end
end
