# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AlpaconCli < Formula
  desc "Alpacon CLI"
  homepage "https://github.com/alpacax/alpacon-cli"
  version "1.2.5"

  on_macos do
    on_intel do
      url "https://github.com/alpacax/alpacon-cli/releases/download/v1.2.5/alpacon-1.2.5-darwin-amd64.tar.gz"
      sha256 "06e5c7008dc4e85ce755aa1471938c1712cdf69d670f400591508ab3615fa9c8"

      def install
        bin.install "alpacon"
      end
    end
    on_arm do
      url "https://github.com/alpacax/alpacon-cli/releases/download/v1.2.5/alpacon-1.2.5-darwin-arm64.tar.gz"
      sha256 "4cae5d4910c40e02e751955ae8034280d72289c6eccc85a1c37660e3622367cc"

      def install
        bin.install "alpacon"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/alpacax/alpacon-cli/releases/download/v1.2.5/alpacon-1.2.5-linux-amd64.tar.gz"
        sha256 "b8ab5be62ebb3e10e65d9ae4dfe199bd60413a9cf542d3af48c2e4f98b814888"

        def install
          bin.install "alpacon"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/alpacax/alpacon-cli/releases/download/v1.2.5/alpacon-1.2.5-linux-arm.tar.gz"
        sha256 "b38d973b15b09fe87f7bccae1d9ebf2b17c3daa0633d49f3901ecb3741674a99"

        def install
          bin.install "alpacon"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/alpacax/alpacon-cli/releases/download/v1.2.5/alpacon-1.2.5-linux-arm64.tar.gz"
        sha256 "09cb6c7ad94018628170c9c4cc3537af077db4eb3aa5a066046d197fcda3a9ec"

        def install
          bin.install "alpacon"
        end
      end
    end
  end
end
